---
alacritty_version: "v0.16.1"

alacritty_install_dir: '/opt/alacritty/alacritty'
alacritty_themes_dir: '/opt/alacritty/alacritty_themes'
alacritty_bin_path: '/usr/local/bin'

alacritty_dmg: 'Alacritty-{{ alacritty_version }}.dmg'
alacritty_dmg_url: 'https://github.com/alacritty/alacritty/releases/download/{{ alacritty_version }}/{{ alacritty_dmg }}'

alacritty_update_bashrc: false
alacritty_update_aliases: false
